### ISSUE TITLE
🆔 Identity verification

### ISSUE THREAD

**Issue by petrspelos** [petrspelos/todo#12]
## Summary

This endpoints returns OK if the user authenticated correctly.

A feature like this can be useful for front-ends that want to ensure credentials are valid.

## Exceptional behavior

Unauthenticated requests get a standard 401 Unauthorized.

**Comment by Laxynium** [comment]
Hi, could I start working on that issue?

**Comment by petrspelos** [comment]
Hey, @Laxynium!

I'm not sure how familiar you are with ASP.NET Core, but in general...

You simply clone this repository, open the `.sln` in Visual Studio and implement the appropriate ASP.NET Controller. 🙂

**Comment by Laxynium** [comment]
I have created pull request. https://github.com/petrspelos/todo/pull/17
